MARKET: SNP

LOGLEVEL: ERROR

MAX_FILE_AGE: 1

# SNP ports and client IDs
PORT: 1300
PAPER: 1301

CID: 10

MINCUSHION: 0.3 # 30% minimum cushion for responsible marging trading




COVER_MIN_DTE: 4
COVER_STD_MULT: 1.4


VIRGIN_DTE: 7

VIRGIN_PUT_STD_MULT: 2
VIRGIN_CALL_STD_MULT: 3.5
VIRGIN_MIN_DTE: 2 # minimum days to expiration for naked calls
VIRGIN_QTY_MULT: 0.015 # 1.5% of NLV divided by margin = qty of virgins

PROTECT_DTE: 35
PROTECTION_STRIP: 8 # no of strikes down for longs and up for shorts

MINEXPOPTPRICE: 1.35
MINNAKEDOPTPRICE: 2.1

REAPRATIO: 0.2 # percentage of average cost. Lower the better.

