MARKET: SNP

LOGLEVEL: ERROR

MAX_FILE_AGE: 1.5

COVER_STD_MULT: 0.82
COVER_MIN_DTE: 4

VIRGIN_DTE: 35
VIRGIN_STD_MULT: 2.2
VIRGIN_QTY_MULT: 0.02 # 2% of NLV divided by margin = qty

PROTECTION_STRIP: 1 # strike down for longs and up for shorts
MINEXPOPTPRICE: 0.2

# SNP ports and client IDs
PORT: 1300
PAPER: 1301

CID: 10